name: build

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

defaults:
  run:
    shell: bash
    working-directory: process

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: |
        npm install
    - run: |
        sudo apt update
    - run: |
        sudo apt install make
    - run: |
        make
