name: 'build and test run'

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

defaults:
  run:
    shell: bash
    working-directory: process

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '18'
    - run: |
        npm install
    - run: |
        sudo apt update
    - run: |
        sudo apt install make
    - run: |
        make
    - run: |
        node dist/main --test
