name: update

on:
  schedule:
  - cron: "55 0,12,18,21 * * *"
  workflow_dispatch:

defaults:
  run:
    shell: bash
    working-directory: process

jobs:
  update:

    runs-on: ubuntu-20.04
    timeout-minutes: 15

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - run: |
        npm install
    - run: |
        sudo apt update
    - run: |
        sudo apt install make
    - run: |
        make
    - run: |
        node dist/main
    - uses: EndBug/add-and-commit@v7
      with:
        add: 'output'
        author_name: GitHub Actions
        author_email: actions@github.com
        message: 'Updating output files (GitHub action)'
