name: update

on:
  schedule:
  - cron: "40 * * * *"

jobs:
  update:

    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: |
        cd process
        npm install
    - run: |
        sudo apt update
        sudo apt install make
    - run: |
        cd process
        make
    - run: |
        cd process
        node dist/main
    - uses: EndBug/add-and-commit@v7
      with:
        add: 'output'
        author_name: GitHub Actions
        author_email: actions@github.com
        message: 'Updating output files (GitHub action)'
