name: update

on:
  schedule:
  - cron: "55 * * * *"
  workflow_dispatch:

defaults:
  run:
    shell: bash
    working-directory: process

jobs:
  update:

    runs-on: ubuntu-20.04
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: |
        npm install
    - run: |
        sudo apt update
    - run: |
        sudo apt install make
    - run: |
        make
    - run: |
        node dist/main
    - uses: EndBug/add-and-commit@v7
      with:
        add: 'output'
        author_name: GitHub Actions
        author_email: actions@github.com
        message: 'Updating output files (GitHub action)'
